### ISSUE TITLE
什么时候才能更新，去除 内部依赖？

### ISSUE THREAD

**Issue by xiangyunup** [alibaba/bulbasaur#2]
<parent> 
    <groupId>com.taobao</groupId>  
    <artifactId>parent</artifactId>  
    <version>1.0.3</version> 
  </parent>

**Comment by fromcth** [comment]
去掉提交了。

**Comment by xiangyunup** [comment]
> 去掉提交了。

终于等到你，还好我没放弃，可惜可能是我能力不够，最终还是没能成功打包；
遇到两个问题，
1.一些jar的版本依赖找不到（可自行调整）;
2.core 打包报错我不知道为什么会去读取一个不存在的配置文件（卡在这了。。。）。
.[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.5:resources (default-resources) on project bulbasaur-core: Error loading property file 'C:\Users\yunba\antx.properties' -> [Help 1]

**Comment by xiangyunup** [comment]
> 去掉提交了。

终于等到你，还好我没放弃，可惜可能是我能力不够，最终还是没能成功打包；
遇到两个问题，
一、.一些jar的版本依赖找不到;
1、com.alibaba.toolkit.common.lang
2、org.springframework：spring:999-not-exist-v3
3、com.taobao.diamond：diamond-client：3.6.9
4、一些maven插件的会找不到，是否需要指定版本
二、.core 打包报错我不知道为什么会去读取一个不存在的配置文件（卡在这了。。。）。以下为错误信息：
.[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.5:resources (default-resources) on project bulbasaur-core: Error loading property file 'C:\Users\yunba\antx.properties' -> [Help 1]

**Comment by fromcth** [comment]
> 的配置文件（卡在这了。。。）。以下为错误信息：
> .[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-

1. jar 找不到的问题。我处理一下代码干掉。你也可以直接pom 里面删除
2. 页面卡住，其实是用到了阿里的auto-config组件。你可以创建一下这个文件\Users\yunba\antx.properties，就可以过去了。

**Comment by xiangyunup** [comment]
> > 的配置文件（卡在这了。。。）。以下为错误信息：
> > .[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-
> 
> 1. jar 找不到的问题。我处理一下代码干掉。你也可以直接pom 里面删除
> 2. 页面卡住，其实是用到了阿里的auto-config组件。你可以创建一下这个文件\Users\yunba\antx.properties，就可以过去了。

您好，我再次尝试每个目录新建了配置文件后，并注释掉了一些找不到的JAR 构建成功，但是我并不知道这能不能运行；
antx.properties 这个配置文件，是否可以去掉，之前说的那些jar 是否可以去掉，包括下面这些也是找不到的：
com.taobao.hsf：：hsfstarter：1.0.1-SNAPSHOT
com.taobao.hsf：hsf.unit：1.0.1
com.taobao.hsf：hsfunit：1.0.5-SNAPSHOT
om.taobao.test：itest：1.3-poi37-SNAPSHOT

**Comment by xiangyunup** [comment]
> > 的配置文件（卡在这了。。。）。以下为错误信息：
> > .[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-
> 
> 1. jar 找不到的问题。我处理一下代码干掉。你也可以直接pom 里面删除
> 2. 页面卡住，其实是用到了阿里的auto-config组件。你可以创建一下这个文件\Users\yunba\antx.properties，就可以过去了。

ScheduleMachineTest.java :44

这个测试类好像是不完整的，有错误；

**Comment by fromcth** [comment]
> > > 的配置文件（卡在这了。。。）。以下为错误信息：
> > > .[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-
> > 
> > 
> > 
> > 1. jar 找不到的问题。我处理一下代码干掉。你也可以直接pom 里面删除
> > 2. 页面卡住，其实是用到了阿里的auto-config组件。你可以创建一下这个文件\Users\yunba\antx.properties，就可以过去了。
> 
> ScheduleMachineTest.java :44
> 
> 这个测试类好像是不完整的，有错误；

测试类没有跟着更新，我后面再找时间补上去
