### ISSUE TITLE
项目内数据库初始化语句缺失字段

### ISSUE THREAD

**Issue by DaredevilDA** [alibaba/bulbasaur#3]
缺失字段如下：
refund_bulbasaur_d.definition_alias
refund_bulbasaur_p.alias
refund_bulbasaur_s.alias
refund_bulbasaur_s.exe_info
refund_bulbasaur_t.deal_result

**Comment by fromcth** [comment]
> 缺失字段如下：
> refund_bulbasaur_d.definition_alias
> refund_bulbasaur_p.alias
> refund_bulbasaur_s.alias
> refund_bulbasaur_s.exe_info
> refund_bulbasaur_t.deal_result

这些字段都是无用的，我清理一下项目再提交一下。
