### ISSUE TITLE
模板中设置的失败重试的job，无法唤起

### ISSUE THREAD

**Issue by DaredevilDA** [alibaba/bulbasaur#5]
建议更改代码：
com/tmall/pokemon/bulbasaur/schedule/job/FailedRetryJob.java:33

原：
ScheduleMachine scheduleMachine = scheduleMachineFactory.newInstance(jobDO.getBizId());

更改为：
ScheduleMachine scheduleMachine = scheduleMachineFactory.newInstance(jobDO.getBizId(), jobDO.getDefinitionName());

**Comment by fromcth** [comment]
> 建议更改代码：
> com/tmall/pokemon/bulbasaur/schedule/job/FailedRetryJob.java:33
> 
> 原：
> ScheduleMachine scheduleMachine = scheduleMachineFactory.newInstance(jobDO.getBizId());
> 
> 更改为：
> ScheduleMachine scheduleMachine = scheduleMachineFactory.newInstance(jobDO.getBizId(), jobDO.getDefinitionName());

我新打一个版本处理一下

**Comment by fromcth** [comment]
已经更新代码
