### ISSUE TITLE
目前mapper文件的表名是写死的，变成动态的可设置的是否更灵活

### ISSUE THREAD

**Issue by DaredevilDA** [alibaba/bulbasaur#6]
只需引jar，前缀可设置，并创建带特定前缀的数据库即可，不需重复打包，更改mapper中表名。

目前我这里实现为：
persistModule 增加 <property name="tableNamePrefix" value="refund_"/>配置
所有以DO和DOExample结尾的类继承抽象类，抽象类包含属性 tableNamePrefix

在所有设置上述两种类的地方增加设置setTableNamePrefix(PersistModule.getInstance().getTableNamePrefix())

在所有mapper里 将原表名替换为 ${tableNamePrefix}bulbasaur_X

**Comment by fromcth** [comment]
> mapper里 将

目前项目里面是可以用户传入表的，在配置初始化xml时候指定

![image](https://user-images.githubusercontent.com/3088172/54185393-dd258780-44e3-11e9-9ca2-7f83bd9a7e11.png)

**Comment by DaredevilDA** [comment]
不清楚这个设计理念要不要支持如下场景：
如果几个小组用一套封好的jar，但是连接的是同一个数据库，组内之间用表名前缀区分业务呢？

**Comment by DaredevilDA** [comment]
> > mapper里 将
> 
> 目前项目里面是可以用户传入表的，在配置初始化xml时候指定
> 
> ![image](https://user-images.githubusercontent.com/3088172/54185393-dd258780-44e3-11e9-9ca2-7f83bd9a7e11.png)
不清楚这个设计理念要不要支持如下场景：
如果几个小组用一套封好的jar，但是连接的是同一个数据库，组内之间用表名前缀区分业务呢？

**Comment by DaredevilDA** [comment]
> 目前项目里面是可以用户传入表的，在配置初始化xml时候指定
不清楚这个设计理念要不要支持如下场景：
如果几个小组用一套封好的jar，但是连接的是同一个数据库，组内之间用表名前缀区分业务呢？
